### ISSUE TITLE
not changing weapon skins

### ISSUE THREAD

**Issue by johandrevwyk** [ianlucas/cs2-inventory-simulator-plugin#1]
might be a dumb problem but, it doesnt apply the skin to the weapons, but it does to knives, adding some debug lines and it seems to find everything properly, just not setting it, gamedata outdated maybe?

**Comment by ianlucas** [comment]
Windows or Linux?
Are you using other plugins with it?

**Comment by johandrevwyk** [comment]
Linux, im using a custom multi 1v1 made by myself, it seems to pick up OnEntityCreated, but it doesnt apply the weapon skin, it works for knife tho. Yes the skins are equipped on the website

**Comment by ianlucas** [comment]
I've tested it on Linux yesterday and it was working ok. We hook GiveNamedItem there. Please confirm the following:

1. FollowCS2ServerGuidelines is false.
2. Gamedata is updated with repository.
3. Look for exceptions or errors with the plugin's name (InventorySimulator) in the logs and console.
4. Does the skin name appear on the HUD when you equip it?

Well if everything checks out and you can see no errors in the logs, then no way to debug it without your plugin. Please also test it without your plugin.
