### ISSUE TITLE
stattrak

### ISSUE THREAD

**Issue by normadelic** [ianlucas/cs2-inventory-simulator-plugin#10]
items stattrak is 0 after restart server.

**Comment by normadelic** [comment]
Im self hosting, but still not working, i will donate , couse your work are
amazing

2024-06-24, pr 22:00, Ian Lucas ***@***.***> rašė:

**Comment by normadelic** [comment]
Its seems need to make a store somewhere else, couse web site remix is not
updating the stattrack too. Or maybe im something doing wrong.

2024-06-24, pr 22:18, Sarunas Zydelis ***@***.***> rašė:

**Comment by ianlucas** [comment]
You need to add a record to `ApiCredential` table, with the following:

* `apiKey`: use [a random string](https://www.random.org/strings/) like `raYOZf9J8oXWv8LL`
* `scope`: `stattrak_increment`

Then use the ConVar `invsim_apikey` with that `apiKey`, i.e. `invsim_apikey raYOZf9J8oXWv8LL`.

**Comment by normadelic** [comment]
Easy to say for you :D i will try to figurout how i need to do it :D thank
you for job, keeep it up !

2024-06-24, pr 22:52, Ian Lucas ***@***.***> rašė:

**Comment by normadelic** [comment]
Hello, did you receive my payment on PayPal? Also, I have the same question
I had before; I’m still getting the "statrak failed, check your
invsim_apikey's value" error. I've updated everything, including the skins,
and everything works, but the stattraks just won't save. 🤷‍♂️

2024-06-25, an 00:01, Sarunas Zydelis ***@***.***> rašė:

**Comment by ianlucas** [comment]
Hello Sarunas, please send an email to support at ianlucas dot net and I'll send you an API key.
