### ISSUE TITLE
[BUG] Knifes only applying after death or reconnect.

### ISSUE THREAD

**Issue by SkyJust4Fun** [ianlucas/cs2-inventory-simulator-plugin#12]
Reproducing:

1. Create a new Knife.
2. Equip it
3. Update it (!ws)
4. Win or Lose Round
5. Wont have the knife on the next round

Not sure about gloves on this one only tested knifes.

**Comment by ianlucas** [comment]
Yeah that's the current behavior. The new knife will only be given when the player respawn or given a new knife, if they survive the round it won't refresh their knife.

In the future this will be handled with real time updates.
