### ISSUE TITLE
[BUG] Editing Stickers or Making the same skin already applied with Other Stickers not applying atm.

### ISSUE THREAD

**Issue by SkyJust4Fun** [ianlucas/cs2-inventory-simulator-plugin#13]
Reproducing:

Alternative 1

1. Edit existing skin
2. Add Stickers
3. Say !ws
4. Stickers not applying after buying..

Alternative 2

1. Create same skin as existing one
2. Add stickers to it
3. Say !ws
4. Stickers wont apply after buying.

All of this either update when reconnecting.

**Comment by ianlucas** [comment]
Added this to the list of known issues.

Looks like the server/client caches the stickers IDs in the first person viewmodel and that's why it won't change even if the new stickers are being added as an attribute to the weapon. Due to my lack of deep RE skills this won't be fixed anytime soon.
