### ISSUE TITLE
[REQ] Paints for weapons that natively didn't support them

### ISSUE THREAD

**Issue by haroldtrotter671** [ianlucas/cs2-inventory-simulator-plugin#16]
For example, Urban DDPAT on the Glock. Perhaps have this feature turned off but enabled by a convar.

**Comment by ianlucas** [comment]
I don't want to introduce a config file, if it's a ConVar it'll be applied to all weapons. Any suggestion?

**Comment by haroldtrotter671** [comment]
Would a feature like this be possible? I know https://github.com/Nereziel/cs2-WeaponPaints was able to do this, but through https://inventory.cstrike.app would it be possible. I know there is icon generation that would be difficult, due to the skin not existing so it would require manual creation of icons, but could a placeholder icon go over the custom created item.

**Comment by ianlucas** [comment]
Inventory Simulator's goal is to be as close to the game as possible. This setting would be only applicable for the plugin. Would a ConVar where you set the list of paints it should never use the legacy model work for you? Something like this:

`invsim_bypass_legacy 123,124,125,126`
