### ISSUE TITLE
[REQ] USE+ to use sprays

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator-plugin#17]
In addition to the option of configuring the bind to use sprays, it would be possible to force the plugin to automatically allow players to bind **`USE+`** to use spray as well.

So no matter which key he configures in CS2 for this bind, he automatically uses the spray, the default would be the **E** key in this case.

**Comment by ianlucas** [comment]
Can you give me an example of plugin that uses this key? I don't think we can force this for the client.

**Comment by crashzk** [comment]
Apparently this plugin would have this function, using E makes using the parachute.

https://github.com/Franc1sco/CS2-Parachute

This one too...

https://github.com/schwarper/cs2-parachute/blob/9b755f52da0ba7f77b501dd6430be689f49c72aa/src/cs2-parachute.cs#L82C1-L83C1

**Comment by ianlucas** [comment]
Okay, I can add a ConVar for that, but it'll try to spray a graffiti anytime the player presses E (including when defusing and planting), does it still makes sense for you?

**Comment by crashzk** [comment]
> Okay, I can add a ConVar for that, but it'll try to spray a graffiti anytime the player presses E (including when defusing and planting), does it still makes sense for you?

Yes, this happened in CSGO too, would a ConVar to enable this function or not be possible? In other words, whether or not I want to leave this feature activated.

In CSGO I made some changes, that the spray would only spray if it wasn't planting or defusing the C4 and/or opening doors/ducts. CS2 I don't know if something like that would be possible. Some way to detect when USE is used on something specific.

**Comment by ianlucas** [comment]
Send the link for the plugin in CSGO and I'll keep that in mind.

**Comment by crashzk** [comment]
Plugin source file is attached.

[valvesprays.zip](https://github.com/user-attachments/files/17357125/valvesprays.zip)

**Comment by Hasanovsky** [comment]
For example, you can double-click on the E button
