### ISSUE TITLE
[REQ] Change knife by command within the server

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator-plugin#19]
I know it may be outside the scope of the project, but are you thinking about adding an option so that even if the player doesn't have any skin/knife in their inventory on the website, they can change it to any vanilla knife within the server?

In other words, type `!knife` and it will show a menu of the knives, but if you choose without any skin. Or even name the knife straight like `!karambit` and he gets the karambit.

**Comment by ianlucas** [comment]
Out of scope.
