### ISSUE TITLE
invsim_apikey's error

### ISSUE THREAD

**Issue by 1Mack** [ianlucas/cs2-inventory-simulator-plugin#20]
I'm facing this issue sometimes, but my invsim_apikey's is filled correclty and all my selected skins are showing up for me

Error log: [EROR] (plugin:InventorySimulator) POST /api/increment-item-stattrak failed, check your invsim_apikey's value.

**Comment by ianlucas** [comment]
Well, there isn't much I can do besides adding the full URL in the debug message. Check the URL it's hitting when you get that error again. The code specifically looks for 401 error code to print that message, so your API is returning that if you confirm it's your URL.
