### ISSUE TITLE
[BUG] `!ws` command does not show skin update message

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator-plugin#24]
It only shows the message `"invsim.announce"`

Apparently none of the other phrases are appearing when I type `!ws`.

**Comment by ianlucas** [comment]
It has been a month since I've updated the plugin, either this is an issue with CS# or your server language is misconfigured (or the language file is missing in the plugin directory). Also just a did test in some servers I have and it's working fine.

**Comment by crashzk** [comment]
Strange, is it really working?

I just sent the plugin again, without any changes, I downloaded the most recent release and sent it.
```
[#12:LOADED]: "InventorySimulator" (1.14.0) by Ian Lucas
Inventory Simulator (inventory.cstrike.app)
```

As you can see in the screenshot, just the website message and nothing else, even using the `!ws` command several times.![image](https://github.com/user-attachments/assets/e94a850e-9445-4b3e-9974-a6dd5c57aa65)

**CSSharp Version:** Current API Version: v290 (1.0.290+7929751)

**Meta Version:**
```
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1315
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Nov 17 2024 07:44:50
    Built from: https://github.com/alliedmodders/metamod-source/commit/d1866d0
    Build ID: 1315:d1866d0
    http://www.metamodsource.net/
```

My configuration in **`server.cfg`:**
```
//Inventory Simulator
invsim_hostname cs2.zkservidores.com
invsim_apikey XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
invsim_stattrak_ignore_bots true
invsim_minmodels 1
invsim_ws_enabled true
invsim_ws_cooldown 30
invsim_spraychanger_enabled true
invsim_spray_cooldown 30
invsim_ws_print_full_url false
invsim_spray_on_use true
```

**Comment by ianlucas** [comment]
Check what's `invsim_ws_enabled` value after the server starts to see if it's really being applied.

**Comment by ianlucas** [comment]
Just did a test on my server, and yeah it's working:

![image](https://github.com/user-attachments/assets/7e5fef46-f48e-4db3-8f22-e68dca0dc41f)

![image](https://github.com/user-attachments/assets/b4f60873-bcf9-4bce-896c-d9f4deafda4a)

**Comment by crashzk** [comment]
Cvar marked as **True**.

![image](https://github.com/user-attachments/assets/8aec9ee8-41a6-47a3-bea7-1c68b474f628)

I will resend the version of the most recent release and test everything again... The only difference from the official version is the config and the translation that I put colors in the message.
