### ISSUE TITLE
[REQ] Show equipped agent in team selection menu

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator-plugin#26]
When we use what we have in the CS2 inventory, even when we click to select a team, it shows our agent if he is equipped.

However, I noticed that on the Inventory Simulator website, even though I have them equipped there, it does not show them on the server. Would it be possible to implement this feature? Show the agent that we equipped on the website when selecting a team?

![20241229183545_1](https://github.com/user-attachments/assets/6379a277-94f4-42a9-9f37-ac4db4a2e92d)
![Screenshot_1](https://github.com/user-attachments/assets/37803879-332a-4308-b46b-49ddf4564aba)

The agent that shows when I'm in TR/CT is the one I have in my steam inventory. (https://steamcommunity.com/id/crashzk/inventory)

**Comment by ianlucas** [comment]
It's already in the roadmap. No ETA at the moment.
